settings:
  title: 'R-hub Status Page'
  url: 'https://github.com/r-hub' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-r-pkg-org # unique identifier
    name: METACRAN web
    description: 'METACRAN web server.' # default=empty
    url: 'https://www.r-pkg.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api-r-hub-io-rversions
    name: R versions API
    description: 'API for R versions.'
    url: 'https://api.r-hub.io/rversions/resolve/release/linux-ubuntu-22.04'
    linkable: false # allows the title to be a link, default=true

  - id: cranlogs-r-pkg-org
    name: CRAN download logs API
    url: 'https://cranlogs.r-pkg.org/downloads/daily/last-week/igraph'
    linkable: false

  - id: test-failure
    name: 'Testing email on failure'
    url: https://cranlogs.r-pkg.org
    linkable: false

  - id: test-failure2
    name: 'Testing email on failure #2'
    url: https://cranlogs.r-pkg.org
    linkable: false
