settings:
  title: 'R-hub Status Page'
  url: 'https://github.com/r-hub' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: builder2-r-hub-io
    name: R-hub v2
    description: 'The R-hub v2 web app.'
    url: 'https://builder2.rhub.io/api/-/admin/users'
    method: 'GET'
    expectStatus: 401
    linkurl: 'https://r-hub.github.io/rhub/'
    linkable: true

  - id: www-r-pkg-org # unique identifier
    name: METACRAN web
    description: 'METACRAN web server.' # default=empty
    url: 'https://www.r-pkg.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api-r-hub-io-rversions
    name: R versions API
    description: 'API to query current and past R versions.'
    url: 'https://api.r-hub.io/rversions/resolve/release/linux-ubuntu-22.04'
    linkurl: 'https://api.r-hub.io/rversions'
    linkable: true # allows the title to be a link, default=true

  - id: cranlogs-r-pkg-org
    name: CRAN download logs API
    description: 'Database of CRAN package download counts.'
    url: 'https://cranlogs.r-pkg.org/downloads/daily/last-week/igraph'
    linkurl: 'https://cranlogs.r-pkg.org'
    linkable: true

  - id: evercran-r-pkg-org
    name: Evercran
    description: 'Run historical R versions, with historical CRAN.'
    url: 'https://evercran.r-pkg.org/2024/04/12/src/contrib/PACKAGES'
    method: 'HEAD'
    linkurl: 'https://github.com/r-hub/evercran#readme'
    linkable: true

  - id: crandb-r-pkg-rrg
    name: CRANDB
    description: 'Database of CRAN packages'
    url: 'https://crandb.r-pkg.org/dplyr'
    linkurl: 'https://github.com/r-hub/crandb/tree/v2'
